services:
  mysql:
    image: mysql:8.4
    container_name: order-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ifpb
      MYSQL_DATABASE: order
    ports:
      - "3306:3306"
    volumes:
      - order_mysql_data:/var/lib/mysql

volumes:
  order_mysql_data:
