services:
  mysql:
    image: mysql:8.4
    container_name: grpc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pminhasenha"]
      interval: 10s
      timeout: 5s
      retries: 10

  payment:
    build:
      context: ..
      dockerfile: microservices/payment/Dockerfile
    container_name: grpc-payment
    environment:
      ENV: development
      APPLICATION_PORT: 3001
      DATA_SOURCE_URL: root:minhasenha@tcp(mysql:3306)/payment?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy

  shipping:
    build:
      context: ..
      dockerfile: microservices/shipping/Dockerfile
    container_name: grpc-shipping
    environment:
      ENV: development
      APPLICATION_PORT: 3002
      DATA_SOURCE_URL: root:minhasenha@tcp(mysql:3306)/shipping?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy

  order:
    build:
      context: ..
      dockerfile: microservices/order/Dockerfile
    container_name: grpc-order
    environment:
      ENV: development
      APPLICATION_PORT: 3000
      DATA_SOURCE_URL: root:minhasenha@tcp(mysql:3306)/order?charset=utf8mb4&parseTime=True&loc=Local
      PAYMENT_SERVICE_URL: payment:3001
      SHIPPING_SERVICE_URL: shipping:3002
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      payment:
        condition: service_started
      shipping:
        condition: service_started

volumes:
  mysql_data:
